name: Setup Node.js
description: Setup Node.js with npm cache and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '18.20.8'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      shell: bash
