name: Setup Node.js
description: Setup Node.js with npm cache and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version-file: "package.json"
        check-latest: true
        cache: "npm"

    - name: Install dependencies
      run: npm ci
      shell: bash
