name: Docker Publish
description: Build and push Docker image

inputs:
  app-name:
    description: Application name
    required: true
  image-name:
    description: Docker image name (e.g., linagora/tom-server)
    required: true
  dockerfile:
    description: Path to Dockerfile
    required: true
  dockerhub-user:
    description: DockerHub username
    required: true
  dockerhub-password:
    description: DockerHub password
    required: true

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-user }}
        password: ${{ inputs.dockerhub-password }}

    - name: Extract tag name
      id: tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./
        file: ${{ inputs.dockerfile }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ inputs.image-name }}:latest
          ${{ inputs.image-name }}:${{ steps.tag.outputs.tag }}
