/**
 * Application-level custom metrics.
 *
 * Auto-instrumentation already provides the golden signals:
 *   - http.server.duration (latency histogram)
 *   - http.server.request.count (request rate)
 *   - http.server.response.size
 *   - db.client.connections.usage (pg pool)
 *
 * This file defines business-specific metrics that auto-instrumentation
 * cannot infer. Add metrics here only when they represent a domain concept
 * (e.g., lookup hit rate, hash rotation count) — not generic HTTP/DB stats.
 */
import { type Meter, metrics } from "@opentelemetry/api";

const meter: Meter = metrics.getMeter("tom");

// biome-ignore lint/nursery/useExplicitType: appMetrics type is generated by TS from the meter.createCounter calls
export const appMetrics = {
  /** Number of 3PID lookups that returned at least one mapping */
  // lookupHits: meter.createCounter("tom.lookup.hits", {
  //   description: "Lookup requests that returned at least one mapping",
  // }),
  /** Number of 3PID lookups that returned zero mappings */
  // lookupMisses: meter.createCounter("tom.lookup.misses", {
  //   description: "Lookup requests that returned zero mappings",
  // }),
  /** Hash pepper rotation events */
  // pepperRotations: meter.createCounter("tom.pepper.rotations", {
  //   description: "Number of pepper rotation events",
  // }),
  /** Current number of stored hash associations (gauge) */
  // associationCount: meter.createObservableGauge("tom.associations.count", {
  //   description: "Current number of stored hash associations",
  // }),
};

export type AppMetrics = typeof appMetrics;
