name: Build

on:
  workflow_call:
    inputs:
      upload-artifacts:
        type: boolean
        default: false

permissions:
  actions: read
  contents: read

jobs:
  build:
    name: Build Affected Packages
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Setup Nx SHAs
        uses: nrwl/nx-set-shas@v4

      - name: Build
        uses: ./.github/actions/build-affected
        with:
          upload-artifacts: ${{ inputs.upload-artifacts }}
