name: Lint

on:
  workflow_call:
    secrets:
      NX_CLOUD_ACCESS_TOKEN:
        required: false

permissions:
  actions: read
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 2.4.8

      - name: Run lint
        run: npx biome ci . --vcs-enabled=true --no-errors-on-unmatched --max-diagnostics none
