name: CI

on:
  pull_request:
  push:
    branches: [master, dev]
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/_lint.yml
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

  build:
    name: Build
    uses: ./.github/workflows/_build-affected.yml
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

  test:
    name: Test
    needs: [build]
    uses: ./.github/workflows/_test-ci.yml
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

  security:
    name: Security
    uses: ./.github/workflows/_security.yml

  docs:
    name: Docs
    uses: ./.github/workflows/_docs.yml
