# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: publish-tom-federated-identity-service

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Get all src files that have changed
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            packages/federated-identity-service/**/*
            .github/workflows/**
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: linagora/tom-federated-identity-service
      - name: Publish to dockerhub
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./packages/federated-identity-service/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            linagora/tom-federated-identity-service:latest
            linagora/tom-federated-identity-service:${{ steps.date.outputs.date }}
